IF OBJECT_ID ('dbo.SIKABUNGAH_ANAK_KE') IS NOT NULL
	DROP TABLE dbo.SIKABUNGAH_ANAK_KE
GO

CREATE TABLE dbo.SIKABUNGAH_ANAK_KE
	(
	ID_ANAK_KE  NUMERIC (18) IDENTITY NOT NULL,
	NORM_IBU    CHAR (20) NULL,
	NAMA        VARCHAR (255) NULL,
	TGL_LAHIR   DATE NULL,
	ANAK_KE     CHAR (2) NULL,
	JNS_KELAMIN CHAR (2) NULL,
	CREATE_DATE DATETIME NULL
	)
GO

