IF OBJECT_ID ('dbo.SIKABUNGAH_USERDATA') IS NOT NULL
	DROP TABLE dbo.SIKABUNGAH_USERDATA
GO

CREATE TABLE dbo.SIKABUNGAH_USERDATA
	(
	USERID    NUMERIC (18) IDENTITY NOT NULL,
	USERNAME  VARCHAR (32) NOT NULL,
	NAMA_USER VARCHAR (225) NOT NULL,
	PASSWORD  CHAR (100) NULL
	)
GO

