IF OBJECT_ID ('dbo.SIKABUNGAH_KEHAMILAN_KE') IS NOT NULL
	DROP TABLE dbo.SIKABUNGAH_KEHAMILAN_KE
GO

CREATE TABLE dbo.SIKABUNGAH_KEHAMILAN_KE
	(
	ID_KEHAMILAN_KE INT IDENTITY NOT NULL,
	NORM            CHAR (20) NULL,
	NAMA            VARCHAR (255) NULL,
	ALAMAT          TEXT NULL,
	TGL_LAHIR       DATE NULL,
	KEHAMILAN_KE    INT NULL,
	TGL_AKHIR_MENS  DATE NULL,
	STATUS          CHAR (2) NULL,
	CREATE_DATE     DATETIME NULL,
	CONSTRAINT PK_SIKABUNGAH_KEHAMILAN_KE PRIMARY KEY (ID_KEHAMILAN_KE)
	)
GO

