IF OBJECT_ID ('dbo.SIKABUNGAH_STD_TB_ANAK') IS NOT NULL
	DROP TABLE dbo.SIKABUNGAH_STD_TB_ANAK
GO

CREATE TABLE dbo.SIKABUNGAH_STD_TB_ANAK
	(
	MONTH          INT NOT NULL,
	STANDAR_LOW1   DECIMAL (13,10) NOT NULL,
	STANDAR_LOW2   DECIMAL (13,10) NOT NULL,
	STANDAR_NORMAL DECIMAL (13,10) NOT NULL,
	STANDAR_TOP1   DECIMAL (13,10) NOT NULL,
	STANDAR_TOP2   DECIMAL (13,10) NOT NULL,
	JENIS_KELAMIN  CHAR (1) NOT NULL
	)
GO

