IF OBJECT_ID ('dbo.SIKABUNGAH_PERIKSA_KEHAMILAN') IS NOT NULL
	DROP TABLE dbo.SIKABUNGAH_PERIKSA_KEHAMILAN
GO

CREATE TABLE dbo.SIKABUNGAH_PERIKSA_KEHAMILAN
	(
	ID_PERIKSA_KEHAMILAN INT IDENTITY NOT NULL,
	ID_KEHAMILAN_KE      INT NULL,
	NORM                 CHAR (20) NULL,
	TGL_PERIKSA          DATETIME NULL,
	MINGGU_KE            CHAR (2) NULL,
	BERAT_BADAN          DECIMAL (18) NULL,
	TINGGI_BADAN         DECIMAL (18) NULL,
	TENSI                VARCHAR (100) NULL,
	BERAT_BADAN_JANIN    DECIMAL (18) NULL,
	LINGKAR_KEPALA       DECIMAL (18) NULL,
	LINGKAR_PERUT        DECIMAL (18) NULL,
	CREATE_DATE          DATETIME NULL,
	CONSTRAINT PK_SIKABUNGAH_PERIKSA_KEHAMILAN PRIMARY KEY (ID_PERIKSA_KEHAMILAN),
	FOREIGN KEY (ID_KEHAMILAN_KE) REFERENCES dbo.SIKABUNGAH_KEHAMILAN_KE (ID_KEHAMILAN_KE)
	)
GO

